blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import LatestPostsFeed
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # post views
    url(r'^post_list/$', views.post_list, name='post_list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list,name='post_list_by_tag'),
    url(r'^(?P<post_id>\d+)/$', views.post_share,name='post_share'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<postit>[-\w]+)/$',
        views.post_detail,name='post_detail'),
    url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
    url(r'blog manager', views.post_sidebar,name='blog manager'),



    # '''
    # url(r'^$', views.post_list, name='post_list'),
    # # url(r'^$', views.PostListView.as_view(), name='post_list'),
    #
    # url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list,name='post_list_by_tag'),
    #
    # The first pattern will call the post_list view without any optional
    # parameters, while the second pattern will call the view with the tag_slug parameter.
    # '''
    ]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

example/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.sitemaps import PostSitemap
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import logout
sitemaps={'posts':PostSitemap}


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls',namespace='blog',app_name='blog')),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
                                name='django.contrib.sitemaps.views.sitemap'),

    # '''We define a URL pattern that matches with sitemap.xml and uses the sitemap
    # view. The sitemaps dictionary is passed to the sitemap view
    #
    # we can open
    #http://127.0.0.1:8000/sitemap.xml in your browser
    #
    #
    # '''
    url(r'^contact/$','blog.views.contact', name='contact'),
    url(r'^signup/$','blog.views.signup', name='signup'),
    url(r'^signin/$','blog.views.signin', name='signin'),
    url(r'^aboutus/$','blog.views.aboutus', name='aboutus'),
    url(r'^index/$','blog.views.index',name='index'),
    url(r'^dashboard/$','blog.views.dashboard',name='dashboard'),
    url(r'^edit/$','blog.views.edit',name='edit'),
    #url(r'^password_reset','', name='password_reset'),
    url(r'^t-and-c','blog.views.tandc',name='t-and-c'),
    url(r'^logout/$', 'blog.views.logged_out',name='logout'),
    url(r'^logout-then-login/$','django.contrib.auth.views.logout_then_login',
        name='logout_then_login'),
    url(r'^change-password/$','blog.views.change_password', name='change-password'),
    url(r'^password-change/done/$','django.contrib.auth.views.password_change_done',
        name='password_change_done'),

    url(r'^password-reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
                      'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^password-reset/done/$', 'django.contrib.auth.views.password_reset_done',
                      name='password_reset_done'),
    url(r'^password-reset/compelte/$', 'django.contrib.auth.views.password_reset_complete',
                      name='password_reset_complete'),
    url(r'^subscribe/$','blog.views.subscribe',name='subscribe'),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/forms.py
from .models import Comment
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from .models import Profile, Contact
from django.contrib.auth.forms import SetPasswordForm,PasswordResetForm
from django.utils.translation import ugettext_lazy as _


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('name','email','body')

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    username=forms.CharField( required=True,widget=forms.TextInput,max_length=30)
    first_name=forms.CharField(required=True, widget=forms.TextInput, max_length=30)
    last_name=forms.CharField(required=True, widget=forms.TextInput, max_length=30)
    email=forms.EmailField(required=True, widget=forms.EmailInput, max_length=30)
    password1=forms.CharField(required=True, label='Password', widget=forms.PasswordInput, max_length=10)
    password2=forms.CharField( required=True,label='Confirm password', widget=forms.PasswordInput,max_length=10)


    class Meta:
        model=User
        fields=('username',)

    def clean_password2(self):
        cd=self.cleaned_data

        if cd['password1']!=cd['password2']:
            raise forms.ValidationError('password did not match')
        return cd['password2']

class UserEditForm(forms.ModelForm):

    class Meta:

        model = User
        fields=['username','first_name','last_name','email']
# '''
# 	 UserEditForm : Will allow users to edit their first name, last name, and
# e-mail, which are stored in the built-in User model.
# 	 ProfileEditForm : Will allow users to edit the extra data we save in the
# custom Profile model.
# '''
class ProfileEditForm(forms.ModelForm):

    class Meta:

        model=Profile
        fields=['about_author','date_of_birth','photo']

class ContactForm(forms.ModelForm):
    class Meta:
        model=Contact
        fields='__all__'



class PasswordChangeForm(SetPasswordForm):
    error_messages = dict(SetPasswordForm.error_messages, **{
        'password_incorrect': _("Your old password was entered incorrectly. "
                                "Please enter it again."),
    })
    old_password = forms.CharField(label=_("Old password"),
                                   widget=forms.PasswordInput)

    field_order = ['old_password', 'new_password1', 'new_password2']

    def clean_old_password(self):
        """
        Validates that the old_password field is correct.
        """
        old_password = self.cleaned_data["old_password"]
        if not self.user.check_password(old_password):
            raise forms.ValidationError(
                self.error_messages['password_incorrect'],
                code='password_incorrect',
            )
        return old_password

blog/views.py
from django.core.mail import send_mail
from example.settings import EMAIL_FROM
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment, Contact
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from django.core.mail import  send_mail
from .forms import EmailPostForm, CommentForm, ContactForm
from taggit.models import Tag
from django.db.models import Count
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm, UserRegistrationForm, UserEditForm,ProfileEditForm,PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Profile
from django.utils.translation import ugettext_lazy as _

def post_detail(request, year, month, day, postit):
    #import pdb;pdb.set_trace()
    all_tags=Tag.objects.all()


    try:
        post = get_object_or_404(Post,slug=postit)
        # publish__year=year,publish__month=month,publish__day=day)
        # the above field lookup are written as in django 1.9 or above
        # publish__year => publish.year
        # publish__month => publish.month
        # publish__day => publish.day
        # And realated model attrebute can also be accessed by
        # author__username => author.username




    except:
        post=Post.published.filter(slug=postit,status='published')#,publish__year=year,publish__month=month,publish__day=day)




    comments=post.comments.filter(active=True)
    '''
        We are using the manager for related objects we defined as comments using the related_name
        attribute of the relationship in the Comment model.
    '''

    #list of similer post
    post_tag_id=post.tags.values_list('id',flat=True)
    similer_post=Post.published.filter(tags__in=post_tag_id).exclude(id=post.id)

    similer_post=similer_post.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:5]
    comment_form=None
    if request.method == 'POST':
        '''
        if the view is called by a GET request we build a form instance with comment_form = CommentForm() .
        If the request is done via POST, we instantiate the form using the
        submitted with comment_form = CommentForm(data=request.POST) data and validate it using
        the is_valid() method
        '''
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            '''
            We create a new Comment object by calling the form's save() method.
            The save() method creates an instance of the model that the form is linked
            to and saves it to the database. If you call it with commit=False , you create
            the model instance, but you don't save it to the database.
            
            The save() method is available for ModelForm but not for
            Form instances, since they are not linked to any model.
            '''
            new_comment = comment_form.save(commit=False)
            '''
            By doing this, we are specifying that the new comment belongs to the
            given post.
            '''
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
        else:
            comment_form = CommentForm()

    return render(request,'blog/post/detail.html',{'post':post,'comments':comments,
                                                   'comment_form':comment_form,
                                                   'similer_post':similer_post,
                                                   'all_tags':all_tags})
                      #{'post': post,'comments': comments,'comment_form': comment_form})

    # return render(request,'blog/post/original_detail.html',{'post': post})
def post_sidebar(request):
    post=Post()
    latest_post=post.published.order_by('-publish')[:5]
    most_commented_post=post.published.annotate(
        total_comment=Count('comments')).order_by('-total_comment')[:5]
    return render(request,'blog/post/latest_post.html',locals())


def post_list(request,tag_slug=None):
    #import pdb;pdb.set_trace()
    all_tags=Tag.objects.all()

    object_list = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # 1 posts in each page
    page = request.GET.get('page')
    try:

        posts = paginator.page(page)


    except PageNotAnInteger:
    # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
    # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html',{'page': page,'posts': posts,'tag':tag,'all_tags':all_tags})




def post_share(request, post_id):
    # Retrieve post by id
    #import pdb;pdb.set_trace();
    from example.settings import EMAIL_FROM
    post = get_object_or_404(Post, id=post_id, status='published')
    sent=False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # ... send email
            post_url=request.build_absolute_uri(post.get_absolute_url())

            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])

            send_mail(subject, message, EMAIL_FROM,[cd['to']])

            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,'form': form,'sent':sent})


def contact(request):
    #import pdb;pdb.set_trace()
    message=''
    if request.method=='POST':
        form=ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            contact_obj = Contact.objects.create(name=cd['name'],email=cd['email'],phone=cd['phone'],query=cd['query'])
            contact_obj.save()
            message='your message send'


    else:
        form=ContactForm()
    return render(request,'site/contact.html',{'form':form,'message':message})

def aboutus(request):
    abtus='we are '
    return render(request,'site/about-us.html',{'about-us':abtus})

def index(request):
    return render(request,'site/index.html')


def signin(request):

    if request.method == 'POST':
        #import pdb;pdb.set_trace()
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            user = authenticate(username=cd['username'],password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)

                    return render(request,'site/dashboard.html')
                        #HttpResponse('Authenticated successfully')
                else:
                    message='this account is disabled'
                    #return HttpResponse('Disabled account')
                    return render(request, 'site/login.html', {'form': form, 'message': message})

            else:
                message='either username or password is incorrect'
                #return HttpResponse('Invalid login')
                return render(request, 'site/login.html', {'form': form, 'message':message})
    else:
        form = LoginForm()

    return render(request, 'site/login.html', {'form': form})


@login_required
def dashboard(request):
    #import pdb;pdb.set_trace()
     #we have defined a variable section to track which section of the site the user is watching
    return render(request,'site/dashboard.html',{'section':'dashboard'})

@csrf_exempt
def signup(request):


    #import pdb;pdb.set_trace()

    if request.method=="POST":
        user_form=UserRegistrationForm(request.POST)

        if user_form.is_valid():
            new_user = user_form.save(commit=False)



            # '''
            # Instead of saving the raw
            # password entered by the user, we use the set_password() method of the User
            # model that handles encryption to save for safety
            # username=cd['username'],
            # '''
            cd=user_form.cleaned_data
            new_user.set_password(cd['password1'])
            new_user.save()

            new_user.user=request.user

            new_user.username=cd['username']
            new_user.first_name=cd['first_name']
            new_user.last_name=cd['last_name']
            new_user.email=cd['email']
            new_user.save()

            profile = Profile.objects.create(user=new_user)
            profile.save()

            #,id=new_user.id)

            #profile.user_id=request.user.id
            #profile.save()
            messages.info(request,'You registered successfully, Now please login')

            return render(request,'site/register_done.html',locals())
        else:
            messages.error(request,'please try agian, data you entered is not valid')
           #return HttpResponse('data you entered is not valid')
    else:
        user_form=UserRegistrationForm()


    return render(request,'site/sign-up.html',locals())

@csrf_exempt
@login_required
def edit(request):
    #import pdb;pdb.set_trace()
    if request.method=='POST':
        user_form=UserEditForm(instance=request.user, data=request.POST)
        profile_form=ProfileEditForm( data=request.POST,
                                     files=request.FILES)#instance=request.user.profile,
        if user_form.is_valid() and profile_form.is_valid():

templates/blog/base.html
{% load blog_tags %}

{% load static from staticfiles %}
{% load staticfiles %}
{% load static %}
{% get_static_prefix as STATIC_URL %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
    <title>Substance - Professional Bootstrap Template</title>
	<!-- Meta -->
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="">
	<meta name="author" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
	<!-- Favicon -->
	<link href="favicon.html" rel="shortcut icon">
	<!-- Bootstrap Core CSS -->
	<link rel="stylesheet" href="{{STATIC_URL}}css/bootstrap.css" >





	<!-- Template CSS -->
	<link rel="stylesheet" href="{{STATIC_URL}}css/animate.css" >
	<link rel="stylesheet" href="{{STATIC_URL}}css/font-awesome.css" >
	<link rel="stylesheet" href="{{STATIC_URL}}css/nexus.css" >
	<link rel="stylesheet" href="{{STATIC_URL}}css/responsive.css" >
	<link rel="stylesheet" href="{{STATIC_URL}}css/custom.css" >

	<!-- Google Fonts-->
	<link href="http://fonts.googleapis.com/css?family=Lato:400,300" rel="stylesheet" type="text/css">
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" rel="stylesheet" type="text/css">
<!-- JS -->
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.min.js" ></script>
<script type="text/javascript" src="{{STATIC_URL}}js/bootstrap.min.js" ></script>
<script type="text/javascript" src="{{STATIC_URL}}js/scripts.js"></script>
<!-- Isotope - Portfolio Sorting -->
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.isotope.js" ></script>
<!-- Mobile Menu - Slicknav -->
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.slicknav.js" ></script>
<!-- Animate on Scroll-->
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.visible.js" charset="utf-8"></script>
<!-- Slimbox2-->
<script type="text/javascript" src="{{STATIC_URL}}js/slimbox2.js" charset="utf-8"></script>
<!-- Modernizr -->
<script src="{{STATIC_URL}}js/modernizr.custom.js" type="text/javascript"></script>
<!-- End JS -->

</head>
<body>




{% block topheader %} {% include "blog/header.html"%}      {% endblock%}


<!-- === CONTENT === -->
		<!--<div id="content" class="container">-->
			<!--<div class="row margin-vert-30">-->
				<!--<div class="col-md-12 margin-top-30">-->
{% block content %}


{% endblock %}

		<!--</div>-->
			<!--</div>-->
		<!--</div>-->
		 <!--=== END CONTENT === -->
{% block footer %} {% include "blog/footer.html"%} {%endblock%}

<p><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a></p>

</body>
</html>

templates/blog/blank_blog.html
<!-- === BEGIN HEADER === -->
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<!-- Title -->

</head>
<body>



<div id="sidebar">
        <p> hello every one this my blog, i have written {% total_post %} posts so far</p>
        <h3>latest post
        {% get_latest_post 3 %}</h3>
        <h2>Most Commented Post</h2>
        {% get_most_commented_post 3 as most_commented_post %}
        {% for post in most_commented_post %}
<li>
    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
</li>
{% endfor %}
    </div>


</body>
</html>
<!-- === END FOOTER === -->

templates/blog/footer.html
{% block footer %}
<!-- === BEGIN FOOTER === -->
		<div id="base">
			<div class="container padding-vert-30">
				<div class="row">
					<!-- Thumbs Gallery -->
					<!--<div class="col-md-3 margin-bottom-20">-->
						<!--<h3 class="margin-bottom-10">Portfolio Highlights</h3>-->
						<!--<div class="thumbs-gallery">-->



							<!--</div>			<div class="clearfix"></div>-->
						<!--</div>-->
						<!-- End Thumbs Gallery -->
						<!-- Contact Details -->
						<div class="col-md-3 margin-bottom-20">
							<h3 class="margin-bottom-10">Contact Details</h3>
							<p>A-76, Sector-3<br />
							Greater Noida West,<br />
							Gautam Budh Nagar,<br />
							Delhi(NCR),<br>
							Ph- 7289817380</p>
							<p>Email: <a href="mailto:devg04@gmail.com">devg04@gmail.com</a><br />
							Website: <a href="http://www.website.com/">www.padoliko.com</a></p>
						</div>
						<!-- End Contact Details -->
						<!-- Sample Menu -->
						<div class="col-md-3 margin-bottom-20" >
							<h3 class="margin-bottom-10">Quick Links</h3>
							<ul class="menu">
								<li>
									<a  href="/aboutus/" >About Us</a>
								</li>
								<li>
									<a  href="/signin/" >Login</a>
								</li>
								<li>
									<a  href="/signup/" >Sign up</a>
								</li>
								<li>
									<a  href="/contact/">Contact us</a>
								</li>
							</ul>
							<div class="clearfix"></div>

						</div>
						<!-- End Sample Menu -->
						<!-- Disclaimer -->
						<div class="col-md-3 margin-bottom-20">
							<h3 class="margin-bottom-10">News Letter</h3>
							<p>SUBSCRIBE OUR NEWS LETTER, We are the very enthusiastic team, working towards the environment and society development</p>
							<form action="/subscribe/" method="post">

								<label>Email : </label>
								<input type="email"  name="email" style="color:black"><p><br>
								<input type="submit" value="subscribe" style="color:black; margin-left:50px">

							</form>
							<div class="clearfix"></div>
						</div>
						<!-- End Disclaimer -->
						<div class="clearfix"></div>
					</div>
				</div>
			</div>
			<!-- Footer Menu -->
			<div id="footer">
				<div class="container">
					<div class="row">
						<div id="copyright" class="col-md-4">
							<p>(c) 2018 This is  Copyright content</p>
						</div>
						<div id="footermenu" class="col-md-8">
							<ul class="list-unstyled list-inline pull-right">
								<li>
									<a href="#" target="_blank" >Social Media Site</a>
								</li>
								<li>
									<a href="#" target="_blank" >Machine Learning</a>
								</li>
								<li>
									<a href="#" target="_blank" >E-Commerce Site </a>
								</li>
								<li>
									<a href="#" target="_blank" >Chat Bot</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>



{% endblock %}

templates/blog/header.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
    <!--<meta charset="UTF-8">-->
    <!--<title>Title</title>-->
<!--</head>-->
<!--<body>-->
<!--<a href="#">education</a>-->
<!--<a href="#">health</a>-->
<!--<a href="#">technology</a>-->
<!--<a href="#">life style</a>-->
<!--<a href="#">whatsapp post</a>-->
<!--<a href="#">music and entertainment</a>-->
<!--<a href="#">todu music on red fm</a>-->
<!--</body>-->
<!--</html>-->

<style>
.affix {
      top: 0;
      width: 100%;
      z-index: 9999 !important;
  }

  .affix + .container-fluid {
      padding-top: 70px;
  }
</style>
{% block header %}

<div id="pre_header" class="visible-lg"></div>
	<div id="header" class="container">
		<div class="row">
			<!-- Logo -->
			<div class="logo" style="height:125px; width:225px; border-radius:8px;">
				<a href="index.html" title="">
					<img src="{{STATIC_URL}}img/images1.jpeg" alt="Logo" />
				</a>
			</div>
			<!-- End Logo -->
			<!-- Top Menu -->
			<div class="col-md-12 margin-top-30">
				<div id="hornav" class="pull-right visible-lg">
					<ul class="nav navbar-nav">
						<li><a href="/index/">Home</a></li>
						<li><a href="{% url 'blog:post_list' %}">Blog</a></li>
						<li><a href="/contact/">Contact us</a></li>
						<li><a href="/aboutus/">About us</a></li>
						{% if not request.user.is_authenticated %}
						<li><a href="/signin/">Sign in</a></li>
						<li><a href="/signup/">Sign up</a></li>
						{%endif%}
						{% if request.user.is_authenticated %}
						<li class="parent"><span>{{request.user.first_name}}</span>
									<ul>
										<li><a href="/dashboard/">My Home</a>
										<li><a href="/edit/">Update Profile</a></li>
										<li><a href="/change-password/">Change Password</a></li>
										<li><a href="/admin/">Blog Admin</a></li>
										<li><a href="/logout/">Logout</a></li>
									</ul>
								</li>
						{%endif%}
					</ul>
				</div>
				</div>
				<div class="clear"></div>
				<!-- End Top Menu -->
			</div>
		</div>

		<!-- === END HEADER === -->
{% endblock %}

templates/blog/social-strip.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <style>


/*=========================
  Icons
 ================= */

/* footer social icons */
ul.social-network {
    list-style: none;
	display: inline;
	margin-left:0 !important;
	padding: 0;
}
ul.social-network li {
	display: inline;
	margin: 0 5px;
}


/* footer social icons */
.social-network a.icoRss:hover {
	background-color: #F56505;
}
.social-network a.icoFacebook:hover {
	background-color:#3B5998;
}
.social-network a.icoTwitter:hover {
	background-color:#33ccff;
}
.social-network a.icoGoogle:hover {
	background-color:#BD3518;
}
.social-network a.icoVimeo:hover {
	background-color:#0590B8;
}
.social-network a.icoLinkedin:hover {
	background-color:#007bb7;
}
.social-network a.icoRss:hover i, .social-network a.icoFacebook:hover i, .social-network a.icoTwitter:hover i,
.social-network a.icoGoogle:hover i, .social-network a.icoVimeo:hover i, .social-network a.icoLinkedin:hover i {
	color:#fff;
}
a.socialIcon:hover, .socialHoverClass {
	color:#44BCDD;
}

.social-circle li a {
	display:inline-block;
	position:relative;
	margin:0 auto 0 auto;
	-moz-border-radius:50%;
	-webkit-border-radius:50%;
	border-radius:50%;
	text-align:center;
	width: 50px;
	height: 50px;
	font-size:20px;
}
.social-circle li i {
	margin:0;
	line-height:50px;
	text-align: center;
}

.social-circle li a:hover i, .triggeredHover {
	-moz-transform: rotate(360deg);
	-webkit-transform: rotate(360deg);
	-ms--transform: rotate(360deg);
	transform: rotate(360deg);
	-webkit-transition: all 0.2s;
	-moz-transition: all 0.2s;
	-o-transition: all 0.2s;
	-ms-transition: all 0.2s;
	transition: all 0.2s;

}
.social-circle i {
	color: #fff;
	-webkit-transition: all 0.8s;
	-moz-transition: all 0.8s;
	-o-transition: all 0.8s;
	-ms-transition: all 0.8s;
	transition: all 0.8s;
}



    </style>
</head>


<body><center>

							<br>
							 		<div class="col-md-12">
                    <ul class="social-network social-circle">

                        <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
									</div>
</center>
</body>
</html>