blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import LatestPostsFeed
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # post views
    url(r'^post_list/$', views.post_list, name='post_list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list,name='post_list_by_tag'),
    url(r'^(?P<post_id>\d+)/$', views.post_share,name='post_share'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<postit>[-\w]+)/$',
        views.post_detail,name='post_detail'),
    url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
    url(r'blog manager', views.post_sidebar,name='blog manager'),



    # '''
    # url(r'^$', views.post_list, name='post_list'),
    # # url(r'^$', views.PostListView.as_view(), name='post_list'),
    #
    # url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list,name='post_list_by_tag'),
    #
    # The first pattern will call the post_list view without any optional
    # parameters, while the second pattern will call the view with the tag_slug parameter.
    # '''
    ]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

example/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.sitemaps import PostSitemap
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import logout
sitemaps={'posts':PostSitemap}


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls',namespace='blog',app_name='blog')),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
                                name='django.contrib.sitemaps.views.sitemap'),

    # '''We define a URL pattern that matches with sitemap.xml and uses the sitemap
    # view. The sitemaps dictionary is passed to the sitemap view
    #
    # we can open
    #http://127.0.0.1:8000/sitemap.xml in your browser
    #
    #
    # '''
    url(r'^contact/$','blog.views.contact', name='contact'),
    url(r'^signup/$','blog.views.signup', name='signup'),
    url(r'^signin/$','blog.views.signin', name='signin'),
    url(r'^aboutus/$','blog.views.aboutus', name='aboutus'),
    url(r'^index/$','blog.views.index',name='index'),
    url(r'^dashboard/$','blog.views.dashboard',name='dashboard'),
    url(r'^edit/$','blog.views.edit',name='edit'),
    #url(r'^password_reset','', name='password_reset'),
    url(r'^t-and-c','blog.views.tandc',name='t-and-c'),
    url(r'^logout/$', 'blog.views.logged_out',name='logout'),
    url(r'^logout-then-login/$','django.contrib.auth.views.logout_then_login',
        name='logout_then_login'),
    url(r'^change-password/$','blog.views.change_password', name='change-password'),
    url(r'^password-change/done/$','django.contrib.auth.views.password_change_done',
        name='password_change_done'),

    url(r'^password-reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
                      'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^password-reset/done/$', 'django.contrib.auth.views.password_reset_done',
                      name='password_reset_done'),
    url(r'^password-reset/compelte/$', 'django.contrib.auth.views.password_reset_complete',
                      name='password_reset_complete'),
    url(r'^subscribe/$','blog.views.subscribe',name='subscribe'),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/forms.py
from .models import Comment
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from .models import Profile, Contact
from django.contrib.auth.forms import SetPasswordForm,PasswordResetForm
from django.utils.translation import ugettext_lazy as _


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('name','email','body')

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    username=forms.CharField( required=True,widget=forms.TextInput,max_length=30)
    first_name=forms.CharField(required=True, widget=forms.TextInput, max_length=30)
    last_name=forms.CharField(required=True, widget=forms.TextInput, max_length=30)
    email=forms.EmailField(required=True, widget=forms.EmailInput, max_length=30)
    password1=forms.CharField(required=True, label='Password', widget=forms.PasswordInput, max_length=10)
    password2=forms.CharField( required=True,label='Confirm password', widget=forms.PasswordInput,max_length=10)


    class Meta:
        model=User
        fields=('username',)

    def clean_password2(self):
        cd=self.cleaned_data

        if cd['password1']!=cd['password2']:
            raise forms.ValidationError('password did not match')
        return cd['password2']

class UserEditForm(forms.ModelForm):

    class Meta:

        model = User
        fields=['username','first_name','last_name','email']
# '''
# 	 UserEditForm : Will allow users to edit their first name, last name, and
# e-mail, which are stored in the built-in User model.
# 	 ProfileEditForm : Will allow users to edit the extra data we save in the
# custom Profile model.
# '''
class ProfileEditForm(forms.ModelForm):

    class Meta:

        model=Profile
        fields=['about_author','date_of_birth','photo']

class ContactForm(forms.ModelForm):
    class Meta:
        model=Contact
        fields='__all__'



class PasswordChangeForm(SetPasswordForm):
    error_messages = dict(SetPasswordForm.error_messages, **{
        'password_incorrect': _("Your old password was entered incorrectly. "
                                "Please enter it again."),
    })
    old_password = forms.CharField(label=_("Old password"),
                                   widget=forms.PasswordInput)

    field_order = ['old_password', 'new_password1', 'new_password2']

    def clean_old_password(self):
        """
        Validates that the old_password field is correct.
        """
        old_password = self.cleaned_data["old_password"]
        if not self.user.check_password(old_password):
            raise forms.ValidationError(
                self.error_messages['password_incorrect'],
                code='password_incorrect',
            )
        return old_password

blog/views.py
from django.core.mail import send_mail
from example.settings import EMAIL_FROM
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment, Contact
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from django.core.mail import  send_mail
from .forms import EmailPostForm, CommentForm, ContactForm
from taggit.models import Tag
from django.db.models import Count
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm, UserRegistrationForm, UserEditForm,ProfileEditForm,PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Profile
from django.utils.translation import ugettext_lazy as _

def post_detail(request, year, month, day, postit):
    #import pdb;pdb.set_trace()
    all_tags=Tag.objects.all()


    try:
        post = get_object_or_404(Post,slug=postit)
        # publish__year=year,publish__month=month,publish__day=day)
        # the above field lookup are written as in django 1.9 or above
        # publish__year => publish.year
        # publish__month => publish.month
        # publish__day => publish.day
        # And realated model attrebute can also be accessed by
        # author__username => author.username




    except:
        post=Post.published.filter(slug=postit,status='published')#,publish__year=year,publish__month=month,publish__day=day)




    comments=post.comments.filter(active=True)
    '''
        We are using the manager for related objects we defined as comments using the related_name
        attribute of the relationship in the Comment model.
    '''

    #list of similer post
    post_tag_id=post.tags.values_list('id',flat=True)
    similer_post=Post.published.filter(tags__in=post_tag_id).exclude(id=post.id)

    similer_post=similer_post.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:5]
    comment_form=None
    if request.method == 'POST':
        '''
        if the view is called by a GET request we build a form instance with comment_form = CommentForm() .
        If the request is done via POST, we instantiate the form using the
        submitted with comment_form = CommentForm(data=request.POST) data and validate it using
        the is_valid() method
        '''
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            '''
            We create a new Comment object by calling the form's save() method.
            The save() method creates an instance of the model that the form is linked
            to and saves it to the database. If you call it with commit=False , you create
            the model instance, but you don't save it to the database.
            
            The save() method is available for ModelForm but not for
            Form instances, since they are not linked to any model.
            '''
            new_comment = comment_form.save(commit=False)
            '''
            By doing this, we are specifying that the new comment belongs to the
            given post.
            '''
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
        else:
            comment_form = CommentForm()

    return render(request,'blog/post/detail.html',{'post':post,'comments':comments,
                                                   'comment_form':comment_form,
                                                   'similer_post':similer_post,
                                                   'all_tags':all_tags})
                      #{'post': post,'comments': comments,'comment_form': comment_form})

    # return render(request,'blog/post/original_detail.html',{'post': post})
def post_sidebar(request):
    post=Post()
    latest_post=post.published.order_by('-publish')[:5]
    most_commented_post=post.published.annotate(
        total_comment=Count('comments')).order_by('-total_comment')[:5]
    return render(request,'blog/post/latest_post.html',locals())


def post_list(request,tag_slug=None):
    #import pdb;pdb.set_trace()
    all_tags=Tag.objects.all()

    object_list = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # 1 posts in each page
    page = request.GET.get('page')
    try:

        posts = paginator.page(page)


    except PageNotAnInteger:
    # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
    # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html',{'page': page,'posts': posts,'tag':tag,'all_tags':all_tags})




def post_share(request, post_id):
    # Retrieve post by id
    #import pdb;pdb.set_trace();
    from example.settings import EMAIL_FROM
    post = get_object_or_404(Post, id=post_id, status='published')
    sent=False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # ... send email
            post_url=request.build_absolute_uri(post.get_absolute_url())

            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])

            send_mail(subject, message, EMAIL_FROM,[cd['to']])

            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,'form': form,'sent':sent})


def contact(request):
    #import pdb;pdb.set_trace()
    message=''
    if request.method=='POST':
        form=ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            contact_obj = Contact.objects.create(name=cd['name'],email=cd['email'],phone=cd['phone'],query=cd['query'])
            contact_obj.save()
            message='your message send'


    else:
        form=ContactForm()
    return render(request,'site/contact.html',{'form':form,'message':message})

def aboutus(request):
    abtus='we are '
    return render(request,'site/about-us.html',{'about-us':abtus})

def index(request):
    return render(request,'site/index.html')


def signin(request):

    if request.method == 'POST':
        #import pdb;pdb.set_trace()
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            user = authenticate(username=cd['username'],password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)

                    return render(request,'site/dashboard.html')
                        #HttpResponse('Authenticated successfully')
                else:
                    message='this account is disabled'
                    #return HttpResponse('Disabled account')
                    return render(request, 'site/login.html', {'form': form, 'message': message})

            else:
                message='either username or password is incorrect'
                #return HttpResponse('Invalid login')
                return render(request, 'site/login.html', {'form': form, 'message':message})
    else:
        form = LoginForm()

    return render(request, 'site/login.html', {'form': form})


@login_required
def dashboard(request):
    #import pdb;pdb.set_trace()
     #we have defined a variable section to track which section of the site the user is watching
    return render(request,'site/dashboard.html',{'section':'dashboard'})

@csrf_exempt
def signup(request):


    #import pdb;pdb.set_trace()

    if request.method=="POST":
        user_form=UserRegistrationForm(request.POST)

        if user_form.is_valid():
            new_user = user_form.save(commit=False)



            # '''
            # Instead of saving the raw
            # password entered by the user, we use the set_password() method of the User
            # model that handles encryption to save for safety
            # username=cd['username'],
            # '''
            cd=user_form.cleaned_data
            new_user.set_password(cd['password1'])
            new_user.save()

            new_user.user=request.user

            new_user.username=cd['username']
            new_user.first_name=cd['first_name']
            new_user.last_name=cd['last_name']
            new_user.email=cd['email']
            new_user.save()

            profile = Profile.objects.create(user=new_user)
            profile.save()

            #,id=new_user.id)

            #profile.user_id=request.user.id
            #profile.save()
            messages.info(request,'You registered successfully, Now please login')

            return render(request,'site/register_done.html',locals())
        else:
            messages.error(request,'please try agian, data you entered is not valid')
           #return HttpResponse('data you entered is not valid')
    else:
        user_form=UserRegistrationForm()


    return render(request,'site/sign-up.html',locals())

@csrf_exempt
@login_required
def edit(request):
    #import pdb;pdb.set_trace()
    if request.method=='POST':
        user_form=UserEditForm(instance=request.user, data=request.POST)
        profile_form=ProfileEditForm( data=request.POST,
                                     files=request.FILES)#instance=request.user.profile,
        if user_form.is_valid() and profile_form.is_valid():

templates/blog/post/detail.html
{% extends "./blog/base.html" %}

{%load blog_tags%}

<!-- === BEGIN CONTENT === -->

{% block content %}
		<div id="content" class="container">

			<div class="row margin-vert-30">


				<div class="col-md-9">
					<div class="blog-post">

						<div class="blog-item-header">
							<!--<div class="blog-post-date pull-left">-->
								<!--<span class="day">#{{post.publish.day}}</span>-->
								<!--<span class="month">#{{post.publish.month}}</span>-->
							<!--</div>-->
							<h2>
							<a href="{{ post.get_absolute_url }}">{{post.title}}

							</a>
							</h2>
						</div>
						<div class="blog-post-details">
							<!-- Author Name -->
							<div class="blog-post-details-item blog-post-details-item-left user-icon">
								<i class="fa fa-user"></i>
								<a href="#">{{post.author}}</a>
							</div>
							<!-- End Author Name -->
							<!-- Tags -->
							{%for tag in post.tags.all%}
							<div class="blog-post-details-item blog-post-details-item-left blog-post-details-tags tags-icon">
								<i class="fa fa-tag"></i>
								<a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{tag.name}}</a> ,

							</div>
							{%endfor%}
							<!-- End Tags -->
							<!-- # of Comments -->
							<div
								class="blog-post-details-item blog-post-details-item-left blog-post-details-item-last comments-icon">
								{% with comments.count as total_comments %}

									<i class="fa fa-comments"></i>
									{{ total_comments }} comment{{ total_comments|pluralize }}


								{%endwith%}
							</div>
							<!-- End # of Comments -->
						</div>
						<div class="blog-item">
							<div class="clearfix"></div>
							<div class="blog-post-body row margin-top-15">
								<!--<div class="col-md-5">-->
									<!--<img class="pull-left" src="{{STATIC_URL}}img/blog/image1.jpg" alt="image1">-->
								<!--</div>-->
								<div class="col-md-12">
									<br>
									<p>{{post.body}}</p>
								</div>
								<div class="col-md-12">
									<p>
									References ,</p>
									<blockquote class="primary">
										<p>
										<em>{{post.references.all}}</em>
										</p>
										<small>
										Someone famous in
										<cite title="Source Title">Source Title</cite>
										</small>
									</blockquote>

								</div>
							</div>
							<br>
							{% include "./blog/social-strip.html"%}<hr><br>







							<!--post sharing by email start-->
							<div class="col-md-6 col-md-offset-3 col-sm-offset-3">
							<div class="panel panel-default">
  							<div class="panel-heading">
    						<h3 class="panel-title">Share "{{ post.title }}" by e-mail</h3>
 							</div>
    						<div class="panel-body">
      						{% include "./blog/post/share.html" %}
  							</div>
							</div>
							</div>


							<!--post sharing by email end-->



							<br><hr>


							<div class="blog-item-footer">
								<!-- About the Author -->
								<div class="blog-author panel panel-default margin-bottom-30">
									<div class="panel-heading">
										<h3>About Author</h3>
									</div>
									<div class="panel-body">
										<div class="row">
											<div class="col-md-2">
												{%for img in post.images.all%}
												<img class="pull-left" height="90" width="70" src="{{img.image.url}}" alt="image1">{%endfor%}
											</div>
											<div class="col-md-10">
												<label>{{post.author}}</label>
												<p>{{post.author}}</p>
											</div>
										</div>
									</div>
								</div>
								<!-- End About the Author -->
								<!-- Comments -->
								<div class="blog-recent-comments panel panel-default margin-bottom-30">
									<div class="panel-heading">
										<h3>Comments</h3>
									</div>
									<ul class="list-group">
										{% for comment in post.comments.all %}
										<li class="list-group-item">

											<div class="row">
												<div class="col-md-2 profile-thumb">
													<a  href="#">
														<img class="media-object" src="{{STATIC_URL}}img/profiles/99.jpg" alt="">
													</a>
												</div>
												<div class="col-md-10">
													<h4>{{comment.name}}, Comment Heading</h4>
													<p>{{ comment.body|truncatewords:10 }}</p>
													<span class="date"><i class="fa fa-clock-o"></i>{{comment.created}} </span>
												</div>
											</div>

										</li>
										{%endfor%}

										

										<!-- Comment Form -->
										<li class="list-group-item">
											<div class="blog-comment-form">
												<div class="row margin-top-20">
													<div class="col-md-12">
														<div class="pull-left">
															<h3>Leave a Comment</h3>
														</div>
													</div>
												</div>

												<div class="row margin-top-20">
													<div class="col-md-12">
                                                    {%csrf_token%}
														<form action="." method="post">
                                                    {%csrf_token%}
															<label>Name</label>
															<div class="row margin-bottom-20">
																<div class="col-md-7 col-md-offset-0">

																	<input name="name" class="form-control" type="text">
																</div>
															</div>

															<label>Email <span>*</span></label>
															<div class="row margin-bottom-20">
																<div class="col-md-7 col-md-offset-0">
																	<input name="email" class="form-control" type="text">
																</div>
															</div>

															<label>Message</label>
															<div class="row margin-bottom-20">
																<div class="col-md-11 col-md-offset-0">
																	<textarea name="body" class="form-control" rows="8"></textarea>
																</div>
															</div>
															
															<p><button class="btn btn-primary" type="submit">post</button></p>
														{%csrf_token%}</form>
                                                        {%csrf_token%}
													</div>
												</div>
											</div>
										</li>
										<!-- End Comment Form -->
									</ul>
									
								</div>
								<!-- End Comments -->
							</div>
							
						</div>
					</div>
					<!-- End Blog Post -->		</div>
					<!-- End Main Column -->
					<!-- Side Column -->


					<div class="col-md-3">
						<!-- Blog Tags -->
						<div class="blog-tags">
							<h3><em>Tags</em></h3>
							<ul class="blog-tags">
								{% for tag in all_tags%}
								<li><a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="blog-tag"><strong>{{tag}}</strong></a></li>
								{%endfor%}

							</ul>			</div>
							<!-- End Blog Tags -->

							<!-- Recent Posts -->
						<div data-spy="affix" data-offset-top="60" data-offset-bottom="200">
							<div class="recent-posts">
								<h3><em>Related Post</em></h3>
								{%for post in similer_post%}

								<ul class="posts-list margin-top-10">
									<li>

										<div class="recent-post">
											<a href="#">
												{%for img in post.images.all%}
												<img class="pull-left" src="{{img.image.url}}" height="60" width="60">
												{%endfor%}
											</a>
											<a href="{{post.get_absolute_url}}" class="posts-list-title"><b>{{post.title}}</b></a>
											<br>
											<span class="recent-post-date">
											{{post.publish.month}} {{post.publish.day}}, {{post.publish.year}}
											</span>
										</div>
										<div class="clearfix"></div>
									</li>

								</ul>
								{%endfor%}
							</div>
								<!-- End Recent Posts -->
						<!--<div class="recent-posts">-->
							<!--<h3>Recent Activity</h3>-->
							<!--#{% get_latest_post %}-->


						<!--</div></div>-->

								<!-- End Side Column -->
							</div>
						</div>
					</div>
					<!-- === END CONTENT === -->
		</div>
					{%endblock%}


<style>
	.content
{
    overflow: hidden;
    position: absolute;
    top: 0px;
    bottom: 0px;
    left: 100px;
    right: 0px;
    padding: 0px 10px;
    overflow: auto;
}
.sidenav
{
    padding: 10px 0;
    position: fixed;
    left: 0px;
    top: 0px;
    bottom: 0px;
    width: 100px; /* same as .content left */
    background-color: #fff;
    border-right: 1px solid #000;
    z-index: 1020;
}
</style>

templates/blog/post/latest_post.html
<div class="recent-post">



{% for post in latest_posts%}
<ul class="post-list margin-top-10">
    <li><div class="recent-post">
        <a href="{{post.get_absolute_url}}">
            {%for img in post.images.all%}
            <img class="pull-left" src="{{img.image.url}}" height="60" width="60">{%endfor%}
        </a>
    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
    <br>
    <span class="recent-post-date">
	{{post.publish.month}} {{post.publish.day}}, {{post.publish.year}}
    </span></div>
    </li>
</ul>

{% endfor %}

</div>

templates/blog/post/list.html

{% extends "./blog/base.html"%}
{%load blog_tags%}

		<!-- === BEGIN CONTENT === -->

{%block content%}

		<div id="content" class="container">

			<div class="row margin-vert-30">
				<!-- Main Column -->
				<div class="col-md-9">
					<!-- Blog Post -->
					{% for post in posts%}
					<div class="blog-post padding-bottom-20">
						<!-- Blog Item Header -->
						<div class="blog-item-header">
							<!-- Date -->
							<!--<div class="blog-post-date pull-left">-->

								<!--<span class="day">#{{post.publish.day}}</span>-->
								<!--<span class="month">#{{post.publish.month}}</span>-->
							<!--</div>-->
							<!-- End Date -->
							<!-- Title -->
							<h2>
							<a href="{{  post.get_absolute_url }}">{{ post.title }}</a>
							</h2>
							<div class="clearfix"></div>
							<!-- End Title -->
						</div>
						<!-- End Blog Item Header -->
						<!-- Blog Item Details -->
						<div class="blog-post-details">
							<!-- Author Name -->
							<div class="blog-post-details-item blog-post-details-item-left user-icon">
								<i class="fa fa-user"></i>
								<a href="#">{{post.author}}</a>
							</div>
							<!-- End Author Name -->
							<!-- Tags -->
							{% for tag in post.tags.all %}
							<div class="blog-post-details-item blog-post-details-item-left blog-post-details-tags tags-icon">
								<i class="fa fa-tag"></i>


								<a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>,
								{% if not forloop.last %}, {% endif %}


							</div>
							{% endfor %}
							<!-- End Tags -->
							<!-- # of Comments -->
							<div
								class="blog-post-details-item blog-post-details-item-left blog-post-details-item-last comments-icon">
								{% with comments.count as total_comments %}


									<i class="fa fa-comments"></i>
									{{ total_comments }} comment{{ total_comments|pluralize }}


								{% endwith %}
							</div>
							<!-- End # of Comments -->
						</div>
						<!-- End Blog Item Details -->
						<!-- Blog Item Body -->
						<div class="blog">
							<div class="clearfix"></div>
							<div class="blog-post-body row margin-top-15">
								<div class="col-md-5">
									{% for img in post.images.all %}
									<img class="pull-left" src="{{ img.image.url }}" height="400" width="350">{%endfor%}
								</div>
								<div class="col-md-7">
									<p>



									{{ post.body|truncatewords:45 }}
									</p>
									<!-- Read More -->
									<a href="{{post.get_absolute_url}}" class="btn btn-primary">
										Read More <i class="icon-chevron-right readmore-icon"></i>
									</a>
									<!-- End Read More -->
								</div>
							</div>
						</div>
						<!-- End Blog Item Body -->
					</div>
					{% endfor %}
					<!-- End Blog Item -->
					<!--###########################################################################-->

					<!-- Pagination -->
					<ul class="pager">

						{% include "pagination.html" with page=posts %}
					</ul>
					<!-- End Pagination -->
				</div>
				<!-- End Main Column -->
				<!-- Side Column -->

				<div class="col-md-3">
					<!-- Blog Tags -->

					<div class="blog-tags">
						<h3><em>Tags</em></h3>
						<ul class="blog-tags">

							{%for tag in all_tags%}
							<li><a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="blog-tag"><strong>{{ tag }}</strong></a>

							</li>
							{%endfor%}
						</ul>
					</div>

				</div>

						<!-- End Blog Tags -->
						<!-- Recent Posts -->

				{% get_most_commented_post 5 as most_commented_post %}

						<div class="recent-posts">
							<h3><em>Most Commented Posts</em></h3>
							{%get_most_commented_post 5 as most_commented_post%}
							{% for post in most_commented_post %}

							<ul class="posts-list margin-top-10">

								<li>
									<div class="recent-post">
                                    <a href="{{post.get_absolute_url}}">
										{%for img in post.images.all%}
											<img class="pull-left" src="{{img.image.url}}" height="60" width="60">{%endfor%}
										</a>
										<a href="{{post.get_absolute_url}}" class="posts-list-title"><b>{{post.title}}</b> </a>
										<br>
										<span class="recent-post-date">
										{{post.publish.month}} {{post.publish.day}}, {{post.publish.year}}
										</span>
									</div>

							</ul>
							{%endfor%}
						</div>
						<!--<div class="recent-posts">-->
							<!--<h3>Recent Activity</h3>-->
							<!--#{% get_latest_post %}-->


						<!--</div>-->
				<div class="clearfix"></div>

				</div>



</div>
{%endblock%}

templates/blog/post/original_list.html
{% extends "./blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
<h1>My Blog</h1>


{%if tags%}
<h2>Posts tagged with "{{tags.name}}"</h2>
{%endif%}

<p class="tags">

{% for tag in post.tags.all %}
<a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
{% if not forloop.last %}, {% endif %}
{% endfor %}
</p>

{% for post in posts %}
<h2>
<a href="{{  post.get_absolute_url }}">{{ post.title }}</a>
</h2>
<p class="tags">Tags
{{post.tags.all|join:', '}}
    {% for tag in post.tags.all %}
<a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
{% if not forloop.last %}, {% endif %}
{% endfor %}
</p>

<p class="date">
Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|truncatewords:30|linebreaks }}
<p>


<a href="{% url 'blog:post_share' post.id %}">
Share this post it is list page
</a>
</p>
{% endfor %}



{% include "pagination.html" with page=posts %}

{% endblock %}